"""Fill the live numbers into dark_mode.svg and light_mode.svg.

Run by .github/workflows/neofetch-card.yml once a day. Queries the GitHub
GraphQL API for repo/star/commit/follower counts and lines of code, then edits
the placeholder <tspan> elements in both SVGs in place.

Layout is not this script's job -- tools/build_neofetch_svg.py owns that, and
writes the dot-leader widths to cache/svg_layout.json so the two stay in sync.

Lines of code are expensive to compute (one GraphQL page per 100 commits per
repo), so cache/<sha256 of username>.txt remembers the per-repo totals and only
re-walks a repository when its commit count changes. That cache file is meant to
be committed.

Environment:
    ACCESS_TOKEN   required. Classic or fine-grained PAT with read access to
                   Followers, Starring, Commit statuses, Contents and Metadata.
    USER_NAME      GitHub login. Defaults to mdsarfarazalam840.
    BIRTHDAY       optional YYYY-MM-DD. If set, Uptime counts from that date
                   instead of from the GitHub account creation date.

Derived from github.com/Andrew6rant/Andrew6rant (today.py), MIT licensed.
"""

import datetime
import hashlib
import json
import os
import time

import requests
from dateutil import relativedelta
from lxml import etree

ACCESS_TOKEN = os.environ.get('ACCESS_TOKEN') or os.environ.get('GH_TOKEN') or os.environ.get('GITHUB_TOKEN')
if not ACCESS_TOKEN:
    raise SystemExit('ACCESS_TOKEN (or GH_TOKEN) is not set')

HEADERS = {'authorization': 'token ' + ACCESS_TOKEN}
USER_NAME = os.environ.get('USER_NAME') or 'mdsarfarazalam840'
BIRTHDAY = os.environ.get('BIRTHDAY')

# Repositories to skip when counting lines of code: forks of huge upstreams and
# anything else where the numbers say nothing about your own work.
IGNORED_REPOS = set()

# Forks are skipped by default. Walking a fork of a busy upstream costs hundreds
# of GraphQL calls and usually contributes nothing, because only commits authored
# by you are counted. Set SKIP_FORKS=0 if you do land real work in your forks.
SKIP_FORKS = os.environ.get('SKIP_FORKS', '1') not in ('0', 'false', 'False')

# GitHub answers 502 (and occasionally 403) when a history query is too heavy or
# arrives too fast. Both are transient, so back off and try again before giving up.
MAX_RETRIES = 4
RETRY_BACKOFF = 8  # seconds, doubled per attempt

# Number of comment lines at the top of the cache file.
COMMENT_SIZE = 7
# Write the cache back to disk after this many repositories have been re-scanned.
CHECKPOINT_EVERY = 5
CACHE_COMMENT = [
    'This file is generated by neofetch_stats.py. Do not edit it by hand.\n',
    'Each line below is one repository, in this format:\n',
    '  <sha256 of owner/name> <total commits> <my commits> <additions> <deletions>\n',
    'The repository name is hashed so private repository names stay private, and\n',
    'lines are sorted by hash so the daily commit only shows what actually moved.\n',
    'A repository is only re-scanned when its total commit count changes, which\n',
    'keeps the daily GraphQL bill small. Delete this file to force a full rebuild.\n',
]

QUERY_COUNT = {'user_getter': 0, 'follower_getter': 0, 'graph_repos_stars': 0,
               'recursive_loc': 0, 'loc_query': 0}

SVG_FILES = ('dark_mode.svg', 'light_mode.svg')
LAYOUT_FILE = 'cache/svg_layout.json'


def query_count(funct_id):
    QUERY_COUNT[funct_id] += 1


def cache_filename():
    return 'cache/' + hashlib.sha256(USER_NAME.encode('utf-8')).hexdigest() + '.txt'


def format_plural(unit):
    return 's' if unit != 1 else ''


def uptime(start):
    """'X years, X months, X days' since `start`, with a cake on the anniversary."""
    diff = relativedelta.relativedelta(datetime.datetime.today(), start)
    return '{} {}, {} {}, {} {}{}'.format(
        diff.years, 'year' + format_plural(diff.years),
        diff.months, 'month' + format_plural(diff.months),
        diff.days, 'day' + format_plural(diff.days),
        ' 🎂' if (diff.months == 0 and diff.days == 0) else '')


def simple_request(func_name, query, variables):
    """POST a GraphQL query, or raise with enough context to debug the failure."""
    request = requests.post('https://api.github.com/graphql',
                            json={'query': query, 'variables': variables}, headers=HEADERS)
    if request.status_code == 200:
        return request
    raise Exception(func_name, 'has failed with a', request.status_code, request.text, QUERY_COUNT)


def user_getter(username):
    """Returns ({'id': ...}, account creation timestamp)."""
    query_count('user_getter')
    query = '''
    query($login: String!) {
        user(login: $login) {
            id
            createdAt
        }
    }'''
    request = simple_request(user_getter.__name__, query, {'login': username})
    data = request.json()['data']['user']
    return {'id': data['id']}, data['createdAt']


def follower_getter(username):
    query_count('follower_getter')
    query = '''
    query($login: String!) {
        user(login: $login) {
            followers {
                totalCount
            }
        }
    }'''
    request = simple_request(follower_getter.__name__, query, {'login': username})
    return int(request.json()['data']['user']['followers']['totalCount'])


def graph_repos_stars(count_type, owner_affiliation, cursor=None, total=0):
    """Total repository count, or total stars across those repositories."""
    query_count('graph_repos_stars')
    query = '''
    query ($owner_affiliation: [RepositoryAffiliation], $login: String!, $cursor: String) {
        user(login: $login) {
            repositories(first: 100, after: $cursor, ownerAffiliations: $owner_affiliation) {
                totalCount
                edges {
                    node {
                        ... on Repository {
                            nameWithOwner
                            stargazers {
                                totalCount
                            }
                        }
                    }
                }
                pageInfo {
                    endCursor
                    hasNextPage
                }
            }
        }
    }'''
    variables = {'owner_affiliation': owner_affiliation, 'login': USER_NAME, 'cursor': cursor}
    repositories = simple_request(graph_repos_stars.__name__, query, variables).json()['data']['user']['repositories']
    if count_type == 'repos':
        return repositories['totalCount']
    total += sum(edge['node']['stargazers']['totalCount'] for edge in repositories['edges'])
    if repositories['pageInfo']['hasNextPage']:
        return graph_repos_stars(count_type, owner_affiliation, repositories['pageInfo']['endCursor'], total)
    return total


def loc_query(owner_affiliation, cursor=None, edges=None):
    """Every repository plus its total commit count, paged 60 at a time.

    60 is the sweet spot: larger pages time out with a 502, smaller ones need so
    many requests that the anti-abuse limiter starts returning 502 as well.
    """
    query_count('loc_query')
    edges = [] if edges is None else edges
    query = '''
    query ($owner_affiliation: [RepositoryAffiliation], $login: String!, $cursor: String) {
        user(login: $login) {
            repositories(first: 60, after: $cursor, ownerAffiliations: $owner_affiliation) {
                edges {
                    node {
                        ... on Repository {
                            nameWithOwner
                            isFork
                            defaultBranchRef {
                                target {
                                    ... on Commit {
                                        history {
                                            totalCount
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                pageInfo {
                    endCursor
                    hasNextPage
                }
            }
        }
    }'''
    variables = {'owner_affiliation': owner_affiliation, 'login': USER_NAME, 'cursor': cursor}
    repositories = simple_request(loc_query.__name__, query, variables).json()['data']['user']['repositories']
    edges += repositories['edges']
    if repositories['pageInfo']['hasNextPage']:
        return loc_query(owner_affiliation, repositories['pageInfo']['endCursor'], edges)

    kept = [edge for edge in edges
            if edge['node']['nameWithOwner'] not in IGNORED_REPOS
            and not (SKIP_FORKS and edge['node']['isFork'])]
    print(f'   {len(kept)} of {len(edges)} repositories counted', flush=True)
    return cache_builder(kept)


def history_request(owner, repo_name, cursor):
    """One page of commit history, retrying the transient failures GitHub throws."""
    query_count('recursive_loc')
    query = '''
    query ($repo_name: String!, $owner: String!, $cursor: String) {
        repository(name: $repo_name, owner: $owner) {
            defaultBranchRef {
                target {
                    ... on Commit {
                        history(first: 100, after: $cursor) {
                            totalCount
                            edges {
                                node {
                                    ... on Commit {
                                        committedDate
                                    }
                                    author {
                                        user {
                                            id
                                        }
                                    }
                                    deletions
                                    additions
                                }
                            }
                            pageInfo {
                                endCursor
                                hasNextPage
                            }
                        }
                    }
                }
            }
        }
    }'''
    variables = {'repo_name': repo_name, 'owner': owner, 'cursor': cursor}
    for attempt in range(MAX_RETRIES):
        # Not simple_request(): a failure here has to leave the partially updated
        # cache intact, otherwise a crash halfway through throws away real work.
        request = requests.post('https://api.github.com/graphql',
                                json={'query': query, 'variables': variables}, headers=HEADERS)
        if request.status_code == 200:
            return request
        if request.status_code not in (403, 429, 500, 502, 503) or attempt == MAX_RETRIES - 1:
            return request
        wait = RETRY_BACKOFF * (2 ** attempt)
        print(f'   {owner}/{repo_name}: HTTP {request.status_code}, retrying in {wait}s', flush=True)
        time.sleep(wait)
    return request


def recursive_loc(owner, repo_name, data):
    """Walk a repository's default branch, counting only commits authored by me.

    Named for the upstream function, but paged with a loop: a repository with
    100k commits would blow the recursion limit long before it ran out of pages.
    """
    addition_total, deletion_total, my_commits, cursor = 0, 0, 0, None
    while True:
        request = history_request(owner, repo_name, cursor)
        if request.status_code != 200:
            force_close_file(data)  # save what we have before the crash
            if request.status_code == 403:
                raise Exception('Too many requests in a short amount of time!\n'
                                "You've hit the undocumented anti-abuse limit!")
            raise Exception('recursive_loc() has failed with a', request.status_code,
                            request.text, QUERY_COUNT)

        branch = request.json()['data']['repository']['defaultBranchRef']
        if branch is None:  # empty repository
            return 0, 0, 0
        history = branch['target']['history']
        for node in history['edges']:
            if node['node']['author']['user'] == OWNER_ID:
                my_commits += 1
                addition_total += node['node']['additions']
                deletion_total += node['node']['deletions']
        if not history['edges'] or not history['pageInfo']['hasNextPage']:
            return addition_total, deletion_total, my_commits
        cursor = history['pageInfo']['endCursor']


def cache_builder(edges, loc_add=0, loc_del=0):
    """Refresh the per-repository cache and return [added, deleted, net, cached].

    The cache is keyed by repository hash rather than by position, so adding,
    removing or reordering repositories costs one re-scan of the repository that
    actually changed instead of a full rebuild.
    """
    entries = read_cache()
    scanned = 0
    for edge in edges:
        name = edge['node']['nameWithOwner']
        repo_hash = hashlib.sha256(name.encode('utf-8')).hexdigest()
        try:
            total_commits = edge['node']['defaultBranchRef']['target']['history']['totalCount']
        except TypeError:  # empty repository
            entries[repo_hash] = (0, 0, 0, 0)
            continue
        if entries.get(repo_hash, (None,))[0] == total_commits:
            continue
        owner, repo_name = name.split('/')
        added, deleted, mine = recursive_loc(owner, repo_name, entries)
        entries[repo_hash] = (total_commits, mine, added, deleted)
        scanned += 1
        # The first run walks every repository and can take half an hour, so
        # checkpoint along the way. If the job is cancelled or times out, the
        # next run picks up where this one stopped instead of starting over.
        if scanned % CHECKPOINT_EVERY == 0:
            write_cache(entries)
            print(f'   checkpoint: {scanned} repositories re-scanned', flush=True)

    # Forget repositories that are no longer counted, so deleted or newly
    # ignored repositories stop inflating the totals.
    counted = {hashlib.sha256(edge['node']['nameWithOwner'].encode('utf-8')).hexdigest()
               for edge in edges}
    entries = {key: value for key, value in entries.items() if key in counted}
    write_cache(entries)

    loc_add += sum(value[2] for value in entries.values())
    loc_del += sum(value[3] for value in entries.values())
    return [loc_add, loc_del, loc_add - loc_del, scanned == 0]


def read_cache():
    """{repo hash: (total commits, my commits, additions, deletions)}."""
    try:
        with open(cache_filename(), 'r', encoding='utf-8') as handle:
            lines = handle.readlines()[COMMENT_SIZE:]
    except FileNotFoundError:
        return {}
    entries = {}
    for line in lines:
        fields = line.split()
        if len(fields) == 5:
            entries[fields[0]] = tuple(int(field) for field in fields[1:])
    return entries


def write_cache(entries):
    """Write the comment block plus one line per repository, hash-sorted.

    Sorted so the daily commit only shows the repositories that actually moved.
    """
    with open(cache_filename(), 'w', encoding='utf-8', newline='\n') as handle:
        handle.writelines(CACHE_COMMENT)
        for repo_hash in sorted(entries):
            handle.write(repo_hash + ' ' + ' '.join(str(value) for value in entries[repo_hash]) + '\n')


def force_close_file(entries):
    """Save whatever has been computed so far, since the caller is about to raise."""
    write_cache(entries)
    print('Error while querying GitHub.', cache_filename(), 'has had its partial data saved.')


def commit_counter():
    """Total commits authored by me, summed from the cache."""
    return sum(value[1] for value in read_cache().values())


def svg_overwrite(filename, layout, **values):
    """Replace the placeholder values in one SVG, re-justifying the dot leaders."""
    tree = etree.parse(filename)
    root = tree.getroot()
    for element_id, value in values.items():
        justify_format(root, element_id, value, layout.get(f'{element_id}_dots', 0))
    tree.write(filename, encoding='utf-8', xml_declaration=True)


def justify_format(root, element_id, new_text, reserve=0):
    """Write a value, then resize the leader before it so the line stays flush.

    leader + value always spans reserve + 2 characters, matching leader() in
    tools/build_neofetch_svg.py. Both scripts have to agree on this or the card's
    right edge drifts every time a number gains a digit.
    """
    if isinstance(new_text, int):
        new_text = f'{new_text:,}'
    new_text = str(new_text)
    find_and_replace(root, element_id, new_text)
    dot_string = ' ' + ('.' * max(0, reserve - len(new_text))) + ' '
    find_and_replace(root, f'{element_id}_dots', dot_string)


def find_and_replace(root, element_id, new_text):
    element = root.find(f".//*[@id='{element_id}']")
    if element is not None:
        element.text = new_text


def perf_counter(funct, *args):
    start = time.perf_counter()
    result = funct(*args)
    return result, time.perf_counter() - start


def formatter(label, difference):
    print('{:<23}'.format('   ' + label + ':'), end='')
    if difference > 1:
        print('{:>12}'.format('%.4f' % difference + ' s '))
    else:
        print('{:>12}'.format('%.4f' % (difference * 1000) + ' ms'))


if __name__ == '__main__':
    print('Calculation times:')
    with open(LAYOUT_FILE, 'r', encoding='utf-8') as handle:
        layout = json.load(handle)

    (OWNER_ID, acc_date), user_time = perf_counter(user_getter, USER_NAME)
    formatter('account data', user_time)

    start_date = (datetime.datetime.strptime(BIRTHDAY, '%Y-%m-%d') if BIRTHDAY
                  else datetime.datetime.strptime(acc_date, '%Y-%m-%dT%H:%M:%SZ'))
    age_data, age_time = perf_counter(uptime, start_date)
    formatter('uptime', age_time)

    total_loc, loc_time = perf_counter(loc_query, ['OWNER', 'COLLABORATOR', 'ORGANIZATION_MEMBER'])
    formatter('LOC (cached)' if total_loc[-1] else 'LOC (no cache)', loc_time)

    commit_data, commit_time = perf_counter(commit_counter)
    formatter('commit counter', commit_time)
    star_data, star_time = perf_counter(graph_repos_stars, 'stars', ['OWNER'])
    formatter('star counter', star_time)
    repo_data, repo_time = perf_counter(graph_repos_stars, 'repos', ['OWNER'])
    formatter('repo counter', repo_time)
    contrib_data, contrib_time = perf_counter(graph_repos_stars, 'repos',
                                              ['OWNER', 'COLLABORATOR', 'ORGANIZATION_MEMBER'])
    formatter('contrib counter', contrib_time)
    follower_data, follower_time = perf_counter(follower_getter, USER_NAME)
    formatter('follower counter', follower_time)

    for filename in SVG_FILES:
        svg_overwrite(filename, layout,
                      age_data=age_data,
                      commit_data=commit_data,
                      star_data=star_data,
                      repo_data=repo_data,
                      contrib_data=contrib_data,
                      follower_data=follower_data,
                      loc_data=total_loc[2],
                      loc_add=total_loc[0],
                      loc_del=total_loc[1])
        print('updated', filename)

    print('Total GitHub GraphQL API calls:', '{:>3}'.format(sum(QUERY_COUNT.values())))
    for funct_name, count in QUERY_COUNT.items():
        print('{:<28}'.format('   ' + funct_name + ':'), '{:>6}'.format(count))
