"""Regenerate the neofetch-style profile cards (dark_mode.svg and light_mode.svg).

Everything about the card's *layout and static content* lives in this file. Run it
whenever you want to change a line, reorder sections, or swap the art:

    python tools/build_neofetch_svg.py

The left column is either plain ASCII (the ASCII_ART constant below) or, when
cache/ascii_art.json exists, a shaded mosaic generated by tools/image_to_ascii.py
--shaded. Delete that file to fall back to the ASCII sigil.

The live numbers (repos, stars, commits, followers, lines of code, uptime) are
filled in later by neofetch_stats.py, which runs in CI. This script only writes
the placeholder values and, crucially, the dot-leader padding those values are
justified against. The widths it reserves are written to cache/svg_layout.json so
neofetch_stats.py stays in sync automatically -- do not hand-edit that file.

Adapted from the profile card idea in github.com/Andrew6rant/Andrew6rant.
"""

import json
import os

# Total width of one info line, in characters. The dot leaders stretch to make
# every line exactly this wide, so the right-hand edge of the card stays flush.
LINE_WIDTH = 66

# The canvas is sized for the widest plausible monospace fallback (advance width
# 0.602em, e.g. DejaVu Sans Mono on Linux) rather than for Consolas, which is
# narrower at 0.55em. GitHub renders the card with whatever it has, so budgeting
# for the wide case is what keeps the last column from being clipped.
CANVAS_WIDTH = 1090
CANVAS_HEIGHT = 530
ART_X = 15          # left column: the art
INFO_X = 440        # right column: the neofetch-style readout
LINE_HEIGHT = 20
FIRST_LINE_Y = 30

# Box the shaded mosaic is fitted into. Its aspect ratio is what the --shaded
# grid in tools/image_to_ascii.py samples for, so change both together.
ART_FILE = 'cache/ascii_art.json'
ART_TOP_Y = 44
ART_WIDTH = 408
ART_HEIGHT = 464
ART_PADDING = 6     # margin between the mosaic and the edge of its panel

# How far a block character rises above the baseline, in em. Consolas gives 0.925
# em, which the card's size-adjust: 109% face turns into about 1.01 em; a bare
# monospace fallback is usually a little shorter. Splitting the difference keeps a
# cell within ~6% of the row pitch either way: too small leaves hairline gaps
# between rows, too large smears each row over the one below it.
ART_BLOCK_RISE = 0.95

THEMES = {
    'dark_mode.svg': {
        'bg': '#161b22', 'fg': '#c9d1d9', 'key': '#ffa657',
        'value': '#a5d6ff', 'add': '#3fb950', 'del': '#f85149', 'cc': '#616e7f',
        # The mosaic keeps the photograph's own tonality -- highlights light,
        # shadows sunk into a dark panel -- on both cards, so the light card gets
        # a dark panel behind the art rather than an inverted-looking negative.
        'art_panel': '#0d1117', 'art_ink': '#e6edf3',
    },
    'light_mode.svg': {
        'bg': '#f6f8fa', 'fg': '#24292f', 'key': '#953800',
        'value': '#0a3069', 'add': '#1a7f37', 'del': '#cf222e', 'cc': '#c2cfde',
        'art_panel': '#0d1117', 'art_ink': '#e6edf3',
    },
}

# Biohazard sigil, to match the ☣ year-progress block in the README.
# Regenerate with tools/image_to_ascii.py if you want different art.
ASCII_ART = r"""
                 ..    ..
              ;:;,.    .,;:;
            :l:.          .:l:
           l$.              .$l
          !@.                .@!
         ,@$                  $@.
         ;@@.  .,:|!!!!|:,.  .@@;
         .@@l ,%%!|:;;:|!%%, l@@.
        ..!@@%,.          .,%@@!..
    ,|%@@@@@@@@l:,.    .,:l@@@@@@@@%|,
  ;%@%!:;;;:!%@@@@@%;;$@@@@@%!:;;;:!%@%;
.l$:.    ,%.  .|@@l. ..%@@|.  .%,    .:$l.
%!       |@,    .l:    :l.    ;@:       !%
|        .@!      %$!!$%      l@.        !
.         |@:     !@@@@!     |@:         .
.          :@l,   !@@@@!   ,%@;          .
            .!$! ,@@@@@@, l$!.
 ..            .:@@@;:@@@:.            ..
 .;;,.       .:$@@!.  .!@@$:.       .,;;.
   .,:||||!l%$$l;.      .;l$$%l!||||:,.
       .,,,,..              ..,,,,.
"""

# --- token helpers -------------------------------------------------------
# A line is a list of tokens. Tokens render in order:
#   key(text)          an orange field name
#   lit(text)          plain punctuation / separators
#   val(text, id)      a value, optionally addressable by neofetch_stats.py
#   dots(id, reserve)  a dot leader. reserve is the number of characters kept
#                      free for the value that follows it; 'auto' stretches the
#                      leader so the whole line lands on LINE_WIDTH.


def key(text):
    return ('key', text)


def lit(text):
    return ('lit', text)


def val(text, ident=None, cls='value'):
    return ('val', text, ident, cls)


def dots(ident=None, reserve='auto'):
    return ('dots', ident, reserve)


def field(name, value, ident=None, reserve='auto'):
    """A whole `. Name: ..... value` line, the common case."""
    tokens = [lit('. ')]
    parts = name.split('.')
    for index, part in enumerate(parts):
        if index:
            tokens.append(key('.'))
        tokens.append(key(part))
    tokens += [lit(':'), dots(f'{ident}_dots' if ident else None, reserve),
               val(value, ident)]
    return tokens


def header(title):
    return [('header', title)]


BLANK = [lit('. ')]

# --- card content -------------------------------------------------------
LINES = [
    header('mdsarfarazalam840@github'),
    field('OS', 'Windows 11, Kali Linux, Android'),
    field('Uptime', '6 years, 0 months, 0 days', 'age_data'),
    field('Host', 'Open Source, Freelance Web & Cloud Work'),
    field('Kernel', 'Full-Stack Developer, Cloud & AI Tinkerer'),
    field('IDE', 'VS Code, Claude Code, Android Studio'),
    BLANK,
    field('Languages.Programming', 'TypeScript, JavaScript, Python'),
    field('Languages.Systems', 'Java, C, C++, PHP'),
    field('Languages.Markup', 'HTML, CSS, JSON, YAML, MDX'),
    field('Languages.Real', 'English, Hindi, Urdu'),
    BLANK,
    field('Stack.Cloud', 'Azure, GCP, AWS, DigitalOcean, Appwrite'),
    field('Stack.Ops', 'Docker, Kubernetes, GitHub Actions'),
    field('Hobbies.Software', 'AI agents, automation, side projects'),
    header('Contact'),
    field('LinkedIn', 'md-alam-bb809240'),
    field('Discord', 'mdsarfaraz'),
    field('X', '@MdSarfaraz840'),
    field('Timezone', 'Asia/Kolkata (IST, UTC+05:30)'),
    header('GitHub Stats'),
    # Two values on one line: the first leader is a fixed width, the second
    # stretches to square up the line.
    [lit('. '), key('Repos'), lit(':'), dots('repo_data_dots', 6), val('146', 'repo_data'),
     lit(' {'), key('Contributed'), lit(': '), val('150', 'contrib_data'), lit('} | '),
     key('Stars'), lit(':'), dots('star_data_dots', 'auto'), val('0', 'star_data')],
    [lit('. '), key('Commits'), lit(':'), dots('commit_data_dots', 'auto'), val('0', 'commit_data'),
     lit(' | '), key('Followers'), lit(':'), dots('follower_data_dots', 10), val('0', 'follower_data')],
    # 11 characters is room for 999,999,999 additions; past that the line grows.
    [lit('. '), key('Lines of Code'), lit(':'), dots('loc_data_dots', 'auto'),
     val('0', 'loc_data'), lit(' ( '), dots('loc_add_dots', 11), val('0', 'loc_add', 'addColor'),
     val('++', None, 'addColor'), lit(', '), dots('loc_del_dots', 11),
     val('0', 'loc_del', 'delColor'), val('--', None, 'delColor'), lit(' )')],
]


def escape(text):
    return text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')


def leader(reserve, value_length):
    """A dot leader sized so leader + value is always `reserve` + 2 characters.

    neofetch_stats.justify_format() rebuilds leaders with this exact rule when it
    writes new numbers in, which is what keeps the card's right edge flush as the
    values grow.
    """
    return ' ' + ('.' * max(0, reserve - value_length)) + ' '


def pairs(tokens):
    """Index the val tokens whose width is absorbed by the leader before them."""
    absorbed = set()
    for index, token in enumerate(tokens[:-1]):
        following = tokens[index + 1]
        if token[0] == 'dots' and token[1] and following[0] == 'val':
            absorbed.add(index + 1)
    return absorbed


def measure(tokens):
    """Character width of a line, treating 'auto' leaders as zero.

    A leader with an id plus the value after it always occupies reserve + 2
    characters, so the value itself is not counted separately.
    """
    absorbed = pairs(tokens)
    total = 0
    for index, token in enumerate(tokens):
        if token[0] in ('key', 'lit'):
            total += len(token[1])
        elif token[0] == 'val':
            if index not in absorbed:
                total += len(token[1])
        elif token[0] == 'dots':
            reserve = token[2]
            if reserve != 'auto':
                total += reserve + 2
    return total


def resolve(tokens):
    """Turn one line's tokens into (rendered tokens, {id: reserved width})."""
    autos = [t for t in tokens if t[0] == 'dots' and t[2] == 'auto']
    if len(autos) > 1:
        raise ValueError("a line may contain at most one 'auto' dot leader")
    slack = LINE_WIDTH - measure(tokens)
    reserves, out = {}, []
    for token in tokens:
        if token[0] == 'dots':
            ident, reserve = token[1], token[2]
            if reserve == 'auto':
                # The value sitting after this leader is already counted in
                # measure(), so the leader gets all remaining slack.
                reserve = slack - 2
                if reserve < 0:
                    raise ValueError(f'line is {-slack} chars too long: {tokens}')
            out.append(('dots', ident, reserve))
            if ident:
                reserves[ident] = reserve
        else:
            out.append(token)
    return out, reserves


def render_line(tokens, y, theme):
    """Render one info line as SVG tspans, plus its reserved-width map."""
    if tokens and tokens[0][0] == 'header':
        title = tokens[0][1]
        # First header doubles as the prompt line, the rest get a leading dash.
        label = title if y == FIRST_LINE_Y else f'- {title} '
        rule = '-' + '—' * max(0, LINE_WIDTH - len(label) - 4) + '-—-'
        return (f'<tspan x="{INFO_X}" y="{y}">{escape(label)}</tspan>{escape(rule)}', {})

    resolved, reserves = resolve(tokens)
    absorbed = pairs(resolved)
    pieces, first, pending = [], True, None
    for index, token in enumerate(resolved):
        if token[0] == 'dots':
            ident, reserve = token[1], token[2]
            ident_attr = f' id="{ident}"' if ident else ''
            # The leader's width depends on the value that follows it, so hold
            # it back until that value is known.
            pending = (ident_attr, reserve, len(pieces))
            pieces.append(None)
            continue
        if token[0] == 'key':
            pieces.append(f'<tspan class="key">{escape(token[1])}</tspan>')
            continue
        if token[0] == 'val':
            text, ident, cls = token[1], token[2], token[3]
            ident_attr = f' id="{ident}"' if ident else ''
            if pending and index in absorbed:
                dots_attr, reserve, slot = pending
                pieces[slot] = f'<tspan class="cc"{dots_attr}>{escape(leader(reserve, len(text)))}</tspan>'
                pending = None
            pieces.append(f'<tspan class="{cls}"{ident_attr}>{escape(text)}</tspan>')
            continue
        text = token[1]
        if first:
            # Anchor the line's x/y on its very first tspan.
            pieces.append(f'<tspan x="{INFO_X}" y="{y}" class="cc">{escape(text)}</tspan>')
        else:
            pieces.append(escape(text))
        first = False
    # Any leader with no value after it just fills its reserved width.
    if pending:
        dots_attr, reserve, slot = pending
        pieces[slot] = f'<tspan class="cc"{dots_attr}>{escape(leader(reserve, 0))}</tspan>'
    if first:
        pieces.insert(0, f'<tspan x="{INFO_X}" y="{y}"></tspan>')
    return (''.join(piece for piece in pieces if piece is not None), reserves)


def load_art():
    """The shaded mosaic from tools/image_to_ascii.py --shaded, if it exists."""
    if not os.path.exists(ART_FILE):
        return None
    with open(ART_FILE, encoding='utf-8') as handle:
        return json.load(handle)


def mix(start, end, amount):
    """Blend two #rrggbb colours, `amount` of the way from start to end."""
    channels = []
    for offset in (1, 3, 5):
        low = int(start[offset:offset + 2], 16)
        high = int(end[offset:offset + 2], 16)
        channels.append(round(low + (high - low) * amount))
    return '#%02x%02x%02x' % tuple(channels)


def art_styles(art, theme):
    """One CSS class per brightness level, panel colour up to full ink."""
    levels = art['levels']
    rules = []
    for level in range(1, levels):
        colour = mix(theme['art_panel'], theme['art_ink'], level / (levels - 1))
        rules.append(f'.m{level:x} {{fill: {colour};}}')
    return '\n'.join(rules)


def art_runs(row):
    """Split a row of hex levels into (level, start column, length) runs."""
    runs, start = [], 0
    while start < len(row):
        end = start
        while end < len(row) and row[end] == row[start]:
            end += 1
        level = int(row[start], 16)
        if level:
            runs.append((level, start, end - start))
        start = end
    return runs


def render_art(art, theme):
    """The mosaic as one tspan per run of equally bright cells.

    Every run is placed at an absolute x and pinned to an exact pixel width with
    textLength, so the grid keeps its geometry whatever monospace font the
    renderer ends up using -- the block characters are squeezed or stretched to
    the mosaic's pitch rather than following the font's own advance width.
    """
    columns, rows = art['columns'], art['rows']
    pitch_x = ART_WIDTH / columns
    pitch_y = ART_HEIGHT / rows
    font_size = pitch_y / ART_BLOCK_RISE
    tspans = []
    for index, row in enumerate(art['grid']):
        baseline = ART_TOP_Y + (index + 1) * pitch_y
        for level, start, length in art_runs(row):
            tspans.append(
                f'<tspan class="m{level:x}" x="{ART_X + start * pitch_x:.2f}"'
                f' y="{baseline:.2f}" textLength="{length * pitch_x:.2f}"'
                f' lengthAdjust="spacingAndGlyphs">{"█" * length}</tspan>')
    panel = (f'<rect x="{ART_X - ART_PADDING}" y="{ART_TOP_Y - ART_PADDING}"'
             f' width="{ART_WIDTH + 2 * ART_PADDING}"'
             f' height="{ART_HEIGHT + 2 * ART_PADDING}" rx="10"'
             f' fill="{theme["art_panel"]}"/>')
    body = (f'{panel}\n<g clip-path="url(#artClip)">\n'
            f'<text x="{ART_X}" y="{ART_TOP_Y}" font-size="{font_size:.3f}px">\n'
            + '\n'.join(tspans) + '\n</text>\n</g>')
    clip = (f'<clipPath id="artClip"><rect x="{ART_X}" y="{ART_TOP_Y}"'
            f' width="{ART_WIDTH}" height="{ART_HEIGHT}"/></clipPath>')
    return clip, body, len(tspans)


def render_ascii(theme):
    """The plain ASCII_ART block, one tspan per line."""
    art_start_y = FIRST_LINE_Y + LINE_HEIGHT  # nudge the art down one row
    tspans = '\n'.join(
        f'<tspan x="{ART_X}" y="{art_start_y + index * LINE_HEIGHT}">{escape(line)}</tspan>'
        for index, line in enumerate(ASCII_ART.strip('\n').split('\n')))
    return '', f'<text x="{ART_X}" y="{FIRST_LINE_Y}" fill="{theme["fg"]}" class="ascii">\n{tspans}\n</text>'


def build(filename, theme):
    art = load_art()
    if art:
        clip, art_markup, _ = render_art(art, theme)
        art_css = '\n' + art_styles(art, theme)
    else:
        clip, art_markup = render_ascii(theme)
        art_css = ''

    info_tspans, reserves = [], {}
    for index, tokens in enumerate(LINES):
        rendered, line_reserves = render_line(tokens, FIRST_LINE_Y + index * LINE_HEIGHT, theme)
        info_tspans.append(rendered)
        reserves.update(line_reserves)

    defs = f'<defs>{clip}</defs>\n' if clip else ''
    svg = f"""<?xml version='1.0' encoding='UTF-8'?>
<svg xmlns="http://www.w3.org/2000/svg" font-family="ConsolasFallback,Consolas,monospace" width="{CANVAS_WIDTH}px" height="{CANVAS_HEIGHT}px" font-size="16px">
<style>
@font-face {{
src: local('Consolas'), local('Consolas Bold');
font-family: 'ConsolasFallback';
font-display: swap;
-webkit-size-adjust: 109%;
size-adjust: 109%;
}}
.key {{fill: {theme['key']};}}
.value {{fill: {theme['value']};}}
.addColor {{fill: {theme['add']};}}
.delColor {{fill: {theme['del']};}}
.cc {{fill: {theme['cc']};}}
text, tspan {{white-space: pre;}}{art_css}
</style>
{defs}<rect width="{CANVAS_WIDTH}px" height="{CANVAS_HEIGHT}px" fill="{theme['bg']}" rx="15"/>
{art_markup}
<text x="{INFO_X}" y="{FIRST_LINE_Y}" fill="{theme['fg']}">
{chr(10).join(info_tspans)}
</text>
</svg>"""

    with open(filename, 'w', encoding='utf-8', newline='\n') as handle:
        handle.write(svg)
    return reserves


if __name__ == '__main__':
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    os.chdir(root)
    art = load_art()
    if art:
        runs = render_art(art, THEMES['dark_mode.svg'])[2]
        print(f"art: shaded mosaic from {art['source']}, "
              f"{art['columns']}x{art['rows']}, {runs} runs")
    else:
        print(f'art: ASCII_ART ({ART_FILE} not found)')
    reserves = {}
    for filename, theme in THEMES.items():
        reserves = build(filename, theme)
        print(f'wrote {filename}')
    os.makedirs('cache', exist_ok=True)
    with open('cache/svg_layout.json', 'w', encoding='utf-8', newline='\n') as handle:
        json.dump(reserves, handle, indent=2, sort_keys=True)
        handle.write('\n')
    print('wrote cache/svg_layout.json')
